---
- name: Deploy a web application
  hosts: multipassvm1, multipassvm2
  become: true 
  tasks:
    - name: Update package repositories and install Node.js and npm
      apt:
        update_cache: true
        name:
        - nodejs
        - npm
        state: present
    - name: Clone git repository
      git:
        repo: https://github.com/iAlan02/api-xample.git
        dest: /home/vadmin/api-xample
        force: true
    - name: Install microk8s
      shell: snap install microk8s --classic
    - name: Enable microk8s addons
      shell: microk8s enable dns dashboard
    - name: Run application manifest
      shell: microk8s kubectl apply -f /home/vadmin/api-xample/manifest.yml
    # - name: Install dependencies
    #   npm:
    #     path: api-xample
    # - name: Create environment variables file
    #   copy:
    #     dest: /home/vadmin/api-xample/.env
    #     content: |
    #       PORT=3000
    #       API_KEY=apiKey9000
    # - name: Stop all node processes
    #   shell: killall node
    #   ignore_errors: true
    # - name: Start the application
    #   command:
    #     chdir: /home/vadmin/api-xample
    #     cmd: npm start
    #   async: 1000
    #   poll: 0
    # - name: Ensure app is running
    #   shell: ps aux | grep node
    #   register: app_status
    # - debug: msg={{app_status.stdout_lines}}-