---
- name: Deploy a web application
  hosts: node01, node02
  become: true
  tasks:
    - name: Clone git repository
      git:
        repo: https://github.com/iAlan02/api-xample.git
        dest: /home/vadmin/api-xample
        force: true
    - name: Update package repositories and install Node.js and npm
      apt:
        update_cache: true
        name:
        - nodejs
        - npm
        state: present
    - name: Install Docker
      shell: snap install docker  
    - name: Build container image
      shell:
        cmd: docker build -t mexico-api .
        chdir: /home/vadmin/api-xample
    - name: Run container
      shell: docker run -d -p 3000:3000 mexico-api
